### PR TITLE
xCode 8.3 build error

### PR DESCRIPTION
**Pull request by misanche**
Hi,

I have been trying to build the project without success.

Always getting:
module.modulemap Redefinition of module 'FeedHenry'

I have modified the name of the module.modulemap for FeedHenry.modulemap and now compiles correctly.

I haven't checked with previous version of xCode, but could be helpful to test for next release.

### CODE REVIEW

**Comment by pb82** [comment]
Merging this as @jhellar has already verified that the fix works with xcode 8.1 (current build farm) and 8.3.2 (latest)

**Comment by rafaeltuelho** [comment]
this also happens with `fh-ios-sdk (objectve-c)` I raised a JIRA on https://issues.jboss.org/browse/FH-4137
